IvoirPub/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from dashboard import views, urls

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^$', views.login_page, name='login'),
    url(r'^login/', views.login_page, name='login'),
    url(r'^register/', views.registre_page, name='register'),
    url(r'^init_config/', views.init_config, name='init_config'),
    url(r'^forget/', views.forget_password_page, name='forget-pass'),
    url(r'^dashboard/', include(('dashboard.urls', 'dashboard_app'), namespace='dashboard_sp')),   
]

dashboard/urls.py
from django.conf.urls import url
from dashboard import views

urlpatterns = [
    url(r'^$', views.home_page, name='home'),
    url(r'^disconnect/', views.disconnect, name='disconnect'),
    url(r'^config/', views.app_config_page, name='config'),
    url(r'^edit_login/', views.edit_login_page, name='edit_login'),
    url(r'^edit_campagne/(?P<cmp_id>[0-9]+)$', views.edit_campagne, name='detail_compagne'),
    url(r'^campagne/(?P<cmp_id>[0-9]+)$', views.campagne_detail_page, name='detail'),
    url(r'^edit_post/(?P<cmp_id>[0-9]+)/(?P<post_id>[0-9]+)$', views.edit_campagne_post, name='post'),
    url(r'^campagne/', views.campagne_home_page, name='campagne'),
    url(r'^ajax/fb_query', views.campagne_control_dashboard, name='fb_query'),
    url(r'^ajax/data', views.facebook_control_dashboard, name='fb_data'),
    url(r'^bilan/', views.dashboard_bilan, name='bilan'),
]

dashboard/forms.py
from django import forms
from dashboard import models
from django.forms import (
    Form, 
    ModelForm, 
    TextInput, 
    CheckboxInput,
    PasswordInput, 
    EmailInput,
    Textarea,
    DateInput,
    TimeInput,
    FileInput
)

class LoginForm(Form):
    
    email = forms.EmailField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': "au-input au-input--full",
                "placeholder":"Adresse E-mail"
                }
            )
        )
    password = forms.CharField(
        max_length=120, 
        widget=forms.PasswordInput(
            attrs={
                'class': "au-input au-input--full",
                "placeholder":"Mot de passe"
                }
            )
        )

    def clean(self):
        return super(LoginForm, self).clean() 



class RegisterForm(ModelForm):
    
    class Meta:
        model = models.Account
        fields = ('email', 'password')
        labels = {
            'email': 'Adresse E-mail',
            'password': 'Mot de passe'
        }
        widgets = {
            'email': EmailInput(
                attrs={
                'class': "au-input au-input--full",
                "placeholder":"exemple: ivoirpub@gmail.com"
                }
            ),
            'password': PasswordInput(
                attrs={
                'class': "au-input au-input--full",
                "placeholder":"password"
                }
            )
        }
        exclude = ('',)




class CampagneForm(ModelForm):

    class Meta:
        model = models.Campagne
        fields = ('title', 'description', 'start_date', 'close_date')
        labels = {
            'title': "Titre de la campagne",
            'description': 'Description',
            'start_date': 'Date de demarrage',
            'close_date': 'Date de la cloture'
        }
        widgets = {
            'title': TextInput(
                attrs={
                'class': "au-input au-input--full",
                "placeholder":"title of campagne"
                }
            ),
            'start_date': DateInput(
                attrs={
                'class': "au-input au-input--full",
                'type': 'date'
                }
            ),
            'close_date': DateInput(
                attrs={
                'class': "au-input au-input--full",
                'type': 'date'
                }
            ),
            'description': Textarea(
                attrs={
                'class': "au-input au-input--full",
                "placeholder":"campagne description",
                "rows": 3,
                }
            )
        }
        exclude = ('state', 'create_date', 'modify', 'account')



class PostForm(ModelForm):

    class Meta:
        model = models.Post
        fields = (
            'title', 
            'poste_date', 
            'poste_heure', 
            'message',
            'pages_posted',
            'data_file')
        labels = {
            'title': "Titre",
            'poste_date': 'Date de publication',
            'poste_heure': 'Heure du poste', 
            'message': 'Message',
            'data_file': 'Ajouter un fichier multi-media',
        }
        widgets = {
            'title': TextInput(
                attrs={
                'class': "au-input au-input--full",
                "placeholder":"Titre du post"
                }
            ),
            'pages_posted': TextInput(
                attrs={
                'class': "au-input au-input--full block-hidden",
                "placeholder":"Titre du post"
                }
            ),
            'poste_date': DateInput(
                attrs={
                'class': "au-input au-input--full",
                'type': 'date'
                }
            ),
            'poste_heure': DateInput(
                attrs={
                'class': "au-input au-input--full",
                'type': 'time'
                }
            ),
            'message': Textarea(
                attrs={
                'class': "au-input au-input--full",
                "placeholder":"Saisissez un beau message pour vos internautes ",
                "rows": 3,
                }
            ),
            'data_file' : FileInput(
                attrs={
                'class': "au-input au-input--full",
                "placeholder":"Aucun fichier selectionné"
                }
            ), 
        }
        exclude = ('is_publish', 'campagne', 'used_file')



class ConfigurationForm(ModelForm):

    class Meta:
        model = models.Configuration
        fields = ('aut_generate', 'default_page')
        labels = {
            'aut_generate': 'Auto generation du token',
            'default_page': 'Page de publication pas defaut'
        }
        widgets = {
        'aut_generate': CheckboxInput(
            attrs={
            'class': "switch-input close",
            }
        ),
        'default_page': TextInput(
            attrs={
            'disabled': 'true',
            'class': "au-input au-input--full",
            "placeholder":"Titre du post"
            })
        }
        exclude = ('account',)

dashboard/views.py
from django.shortcuts import render, redirect
from django.db.utils import IntegrityError
from dashboard import models
from dashboard import forms
from django.http import JsonResponse
from packages.campagne_ctrl import CampagneCtrl
from packages.bilan_chart import ChartJS
from django.views.generic import TemplateView
import datetime 
import json


# Create your views here.
def login_page(request):
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if not form.is_valid():
            return render(request, 'dashboard/login.html', {'form': form})
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        if email and password:
            response = models.Account.objects.filter(email=email, password=password)
            if len(response) == 1:
                user_auth = response[0]
                context = {'email':user_auth.email, 'user_id': user_auth.id}
                request.session['logged_user_id'] = context
                return redirect('/dashboard')
            else :
                context = {
                    'error': "Nom d'utilisateur ou mot de passe incorrect !",
                    'form': form
                }
                return render(request, 'dashboard/login.html', context)
    form = forms.LoginForm()
    return render(request, 'dashboard/login.html', {'form': form})


def edit_campagne(request, cmp_id):
    if 'logged_user_id' not in request.session:
        return redirect('/login')
    logged_user_id = request.session['logged_user_id']
    email = logged_user_id['email']

    account = models.Account.objects.get(id=logged_user_id['user_id'])
    campagne = models.Campagne.objects.get(id=cmp_id)

    context = {'email':email}

    form_default = forms.CampagneForm(initial={
        'title': campagne.title,
        'description' : campagne.description,
        'start_date': campagne.start_date,
        'close_date': campagne.close_date,
    })

    if request.method == 'POST':
        form = forms.CampagneForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            descrip = form.cleaned_data['description']
            start_date = form.cleaned_data['start_date']
            close_date = form.cleaned_data['close_date']

            campagne.title = title
            campagne.description = descrip
            campagne.start_date = start_date
            campagne.close_date = close_date

            today_now = datetime.datetime.now()
            date = today_now.date()

            if close_date != date :
                campagne.statu = False

            campagne.save()
            context['form'] = form_default
            context['success'] = 'Votre campagne a bien été modifié'
        else:
            context['form'] = form
    else:
        context['form'] = form_default
    return render(request, 'dashboard/edit_cmp.html', context)


def home_page(request):
    if 'logged_user_id' not in request.session:
        return redirect('/login')
    logged_user_id = request.session['logged_user_id']
    email = logged_user_id['email']

    account = models.Account.objects.get(id=logged_user_id['user_id'])
    dashboard_data = []
    campagnes = models.Campagne.objects.filter(account=account)

    for item in campagnes :
        posts = models.Post.objects.filter(campagne=item)
        dashboard_data.append({'campagne':item, 'posts':posts})
    context = {'email':email, 'dashboard_data': dashboard_data}
    return render(request, 'dashboard/index.html', context)



def init_config(request):
    if 'logged_user_id' in request.session :
        return render(request, 'dashboard/init_config_app.html')
    else:
        return redirect('/login')



def registre_page(request):
    if request.method == 'POST':
        form = forms.RegisterForm(request.POST)
        if not form.is_valid():
            return render(request, 'dashboard/register.html', {'form': form})
        form.save(commit=True)
        email = form.cleaned_data['email']
        response = models.Account.objects.filter(email=email)
        if len(response) == 1:
            user_auth = response[0]
            context = {'email':user_auth.email, 'user_id': user_auth.id}
            request.session['logged_user_id'] = context
        return redirect('/init_config')
    form = forms.RegisterForm()
    return render(request, 'dashboard/register.html', {'form': form})



def campagne_detail_page(request, cmp_id):
    if 'logged_user_id' not in request.session:
        return redirect('/login')
    logged_user_id = request.session['logged_user_id']
    email = logged_user_id['email']

    account = models.Account.objects.get(id=logged_user_id['user_id'])
    fb_user = models.FacebookUser.objects.filter(account=account)[0]
    pages_posted = models.FPage.objects.filter(fb_user=fb_user)
    campagne = models.Campagne.objects.get(id=eval(cmp_id))
    posts = models.Post.objects.filter(campagne=campagne)

    config = models.Configuration.objects.filter(account=account)[0]
    page_default = models.FPage.objects.filter(page_id=config.default_page)[0]
    context = {

        'email':email, 
        'campagne': campagne, 
        'posts': posts,
        'pages': pages_posted,
        'page_default': page_default
        }

    if request.method == 'POST':
        form = forms.PostForm(request.POST, request.FILES)
        if form.is_valid() :
            title = form.cleaned_data['title']
            poste_date = form.cleaned_data['poste_date']
            poste_heure = form.cleaned_data['poste_heure']
            message = form.cleaned_data['message']
            page_id = form.cleaned_data['pages_posted']
            used_file = False

            if page_id is None:
                page_id = page_default.page_id

            if len(message) == 0:
                message = request.POST['media_message']
                used_file = True

            page = models.FPage.objects.filter(page_id=page_id)[0]

            post = models.Post.objects.create(
                title = form.cleaned_data['title'],
                poste_date = form.cleaned_data['poste_date'],
                poste_heure = form.cleaned_data['poste_heure'],
                message = message,
                used_file = used_file,
                pages_posted = page_id,
                data_file = form.cleaned_data['data_file'],
                campagne = campagne
            )
            post.save()
            return redirect(f'/dashboard/campagne/{cmp_id}')

        else :
            print(form)
            context['form'] = form
            return render(request, 'dashboard/detail_cmp.html', context)
    else :
        context['form'] = forms.PostForm()
        return render(request, 'dashboard/detail_cmp.html', context)



def campagne_home_page(request):
    if 'logged_user_id' not in request.session:
        return redirect('/login')
    logged_user_id = request.session['logged_user_id']
    email = logged_user_id['email']

    account = models.Account.objects.get(id=logged_user_id['user_id'])
    data = models.Campagne.objects.filter(account=account)
    context = {'email':email, 'data':data}

    if request.method == 'POST':
        form = forms.CampagneForm(request.POST)
        if form.is_valid() :
            title = form.cleaned_data['title']
            descrip = form.cleaned_data['description']
            start_date = form.cleaned_data['start_date']
            close_date = form.cleaned_data['close_date']
            resp = models.Campagne(
                title=title,
                description=descrip,
                start_date=start_date,
                close_date=close_date,
                account=account
                )
            resp.save()
            return redirect('/dashboard/campagne')
        else :
            context['form'] = form
            return render(request, 'dashboard/cmp_home.html', context)
    else :
        form = forms.CampagneForm()
        context['form'] = form
        return render(request, 'dashboard/cmp_home.html', context)



def forget_password_page(request):
    return render(request, 'dashboard/forget_password.html')



def edit_login_page(request):
    if 'logged_user_id' in request.session:
        logged_user_id = request.session['logged_user_id']
        email = logged_user_id['email']

        context = {'email':email}

        form_default = forms.RegisterForm(initial={
            'email': email
        })

        if request.method == 'POST':
            form = forms.RegisterForm(request.POST)
            if form.is_valid():
                account = models.Account.objects.filter(email=email)[0]
                account.email = form.cleaned_data['email']
                account.password = form.cleaned_data['password']
                account.save()
                user_auth = account
                session_data = {'email':user_auth.email, 'user_id': user_auth.id}
                request.session['logged_user_id'] = session_data
                context['form']= form_default
                context['success'] = "Votre compte a bien été modifié "
            else:
                context['form']= form
            return render(request, 'dashboard/edit_login.html', context)
        context['form']= form_default
        return render(request, 'dashboard/edit_login.html', context)
    else:
        redirect('/login')


def app_config_page(request):
    if 'logged_user_id' in request.session :
        logged_user_id = request.session['logged_user_id']
        email = logged_user_id['email']
        
        account = models.Account.objects.get(id=logged_user_id['user_id'])

dashboard/templates/dashboard/edit_cmp.html
{% extends 'dashboard/init_template.html' %}
{% block page_title %}Editer{% endblock %}
{% block app_container %}
<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="col-md-12">
                <!-- DATA TABLE -->
                <div class="user-data m-b-30">
                    <div class="container">
                        {% if success %}
                            <div class="sufee-alert alert with-close alert-success alert-dismissible fade show">
                                <span class="badge badge-pill badge-success">Succès</span>
                                {{success}}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                        {% endif %}
                        <h3 class="title-3 m-b-30">
                            <i class="zmdi zmdi-account-calendar"></i>Compte Config</h3>
                        <form action="" method="post">
                            {% csrf_token %} 
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.errors }}
                                    {{ field.label_tag }} {{ field }}
                                </div>
                            {% endfor %}
                            <button class="au-btn au-btn--block au-btn--green m-b-20" type="submit">Modifier</button>
                        </form> 
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 
{% endblock %}  

dashboard/templates/dashboard/index.html
{% extends 'dashboard/init_template.html' %}
{% block page_title %}Accueil{% endblock %}
{% block app_container %}
<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                {% for item in dashboard_data %}
                    <div class="col-lg-6">
                        <div class="au-card au-card--no-shadow au-card--no-pad m-b-40">
                            <div class="au-card-title" style="background-image:url('images/bg-title-01.jpg');">
                                <div class="bg-overlay bg-overlay--blue"></div>
                                <h3>
                                    <i class="zmdi zmdi-account-calendar"></i>{{item.campagne.start_date}}</h3>
                                <a href="{% url 'dashboard_sp:detail' cmp_id=item.campagne.id %}" class="au-btn-plus">
                                    <i class="zmdi zmdi-plus"></i>
                                </a>
                            </div>
                            <div class="au-task js-list-load">
                                <div class="au-task__title">
                                    <p>{{item.campagne.title}}</p>
                                </div>
                                <div class="au-task-list js-scrollbar3">
                                    {% for els in item.posts %}
                                        {% if els.is_publish %}
                                            <div class="au-task__item au-task__item--success">
                                        {% else %}
                                            <div class="au-task__item au-task__item--danger">
                                        {% endif %}
                                                <div class="au-task__item-inner">
                                                    <h5 class="task">
                                                        <a href="{% url 'dashboard_sp:post' post_id=els.id cmp_id=item.campagne.id %}">{{els.title}}</a>
                                                    </h5>
                                                    <span class="time">{{els.poste_date}} {{els.poste_heure}}</span>
                                                </div>
                                            </div>
                                    {% endfor%}
                                </div>
                                <div class="au-task__footer">
                                    <a href="{% url 'dashboard_sp:detail' cmp_id=item.campagne.id %}" class="au-btn au-btn-icon au-btn--green au-btn--small mb-1">
                                        Detail</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/init_template.html
{% extends 'dashboard/base.html' %}
{% block page_title %}{% endblock %}
{% load static %}
{% block page_container %}
    <!-- HEADER MOBILE-->
    <header class="header-mobile d-block d-lg-none">
        <div class="header-mobile__bar">
            <div class="container-fluid">
                <div class="header-mobile-inner">
                    <a class="logo" href="index.html">
                        <img class="logo" src="{% static 'dashboard/images/icon/logo.png' %}" alt="CoolAdmin" />
                    </a>
                    <button class="hamburger hamburger--slider" type="button">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
                    </button>
                </div>
            </div>
        </div>
        <nav class="navbar-mobile">
            <div class="container-fluid">
                <ul class="navbar-mobile__list list-unstyled">
                    <li>
                        <a class="js-arrow" href="{% url 'dashboard_sp:home' %}"><i class="fas fa-tachometer-alt"></i>Dashboard</a>
                    </li>
                    <li class="active has-sub">
                        <a href="{% url 'dashboard_sp:campagne' %}"><i class="fas fa-table"></i>Campagne</a>
                    </li>
                    <li>
                        <a href="{% url 'dashboard_sp:bilan' %}"><i class="fas fa-chart-bar"></i>Bilan</a>
                    </li>
                    <li class="js-arrow open">
                        <a href="#"><i class="zmdi zmdi-settings"></i>Parametre</a>
                        <ul class="list-unstyled navbar__sub-list js-sub-list" style="display: block;">
                            <li>
                                <a href="{% url 'dashboard_sp:config' %}">Général</a>
                            </li>
                            <li>
                                <a href="{% url 'dashboard_sp:edit_login' %}">Compte</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <!-- END HEADER MOBILE-->

    <!-- MENU SIDEBAR-->
    <aside class="menu-sidebar d-none d-lg-block">
        <div class="logo">
            <a href="#">
                <img class="logo" src="{% static 'dashboard/images/icon/logo.png' %}" alt="CoolAdmin" />
            </a>
        </div>
        <div class="menu-sidebar__content js-scrollbar1">
            <nav class="navbar-sidebar">
                <ul class="list-unstyled navbar__list">
                    <li>
                        <a class="js-arrow" href="{% url 'dashboard_sp:home' %}"><i class="fas fa-tachometer-alt"></i>Dashboard</a>
                    </li>
                    <li>
                        <a href="{% url 'dashboard_sp:campagne' %}"><i class="fas fa-table"></i>Campagne</a>
                    </li>
                    <li>
                        <a href="{% url 'dashboard_sp:bilan' %}"><i class="fas fa-chart-bar"></i>Bilan</a>
                    </li>
                    <li class="js-arrow open">
                        <a href="#"><i class="zmdi zmdi-settings"></i>Parametre</a>
                        <ul class="list-unstyled navbar__sub-list js-sub-list" style="display: block;">
                            <li>
                                <a href="{% url 'dashboard_sp:config' %}">Général</a>
                            </li>
                            <li>
                                <a href="{% url 'dashboard_sp:edit_login' %}">Compte</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </aside>
    <!-- END MENU SIDEBAR-->

    <!-- PAGE CONTAINER-->
    <div class="page-container">
        <!-- HEADER DESKTOP-->
        <header class="header-desktop">
            <div class="section__content section__content--p30">
                <div class="container-fluid">
                    <div class="header-wrap">
                        <div></div>
                        <div class="header-button">
                            <div class="noti-wrap">
                                <div class="noti__item js-item-menu">
                                    <i class="zmdi zmdi-notifications"></i>
                                    <span class="quantity">3</span>
                                    <div class="notifi-dropdown js-dropdown">
                                        <div id="notification">

                                        </div>
                                        <div class="notifi__footer">
                                            <a href="{% url 'dashboard_sp:home' %}">Actualiser</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="account-wrap">
                                <div class="account-item clearfix js-item-menu">
                                    <div class="image">
                                        <img src="{% static 'dashboard/images/icon/avatar-01.png' %}" alt="John Doe" />
                                    </div>
                                    <div class="content">
                                        <a class="js-acc-btn" href="#">{{username}}</a>
                                    </div>
                                    <div class="account-dropdown js-dropdown">
                                        <div class="info clearfix">
                                            <div class="image">
                                                <a href="#">
                                                    <img src="{% static 'dashboard/images/icon/avatar-01.png' %}" alt="John Doe" />
                                                </a>
                                            </div>
                                            <div class="content">
                                                <h5 class="name">
                                                    <a href="#">{{username}}</a>
                                                </h5>
                                                <span class="email">{{email}}</span>
                                            </div>
                                        </div>
                                        <div class="account-dropdown__body">
                                            <div class="account-dropdown__item">
                                                <a href="{% url 'dashboard_sp:edit_login' %}"><i class="zmdi zmdi-account"></i>Compte</a>
                                            </div>
                                            <div class="account-dropdown__item">
                                                <a href="{% url 'dashboard_sp:config' %}"><i class="zmdi zmdi-settings"></i>Parametre</a>
                                            </div>
                                        </div>
                                        <div class="account-dropdown__footer">
                                            <a href="{% url 'dashboard_sp:disconnect' %}"><i class="zmdi zmdi-power"></i>Se Déconnecter</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- HEADER DESKTOP-->

        <!-- MAIN CONTENT-->
        {% block app_container %}
        {% endblock %}    
        <!-- END MAIN CONTENT-->
        <!-- END PAGE CONTAINER-->
    </div>
{% endblock %}

{% block ajax_block %}
<!-- <script src="{% static 'dashboard/js/campagne-ctrl.js' %}"></script> -->
<script>
    (()=>{
        var dataLenght = 0
        document.querySelector('.quantity').textContent = dataLenght
        setInterval(
            ()=>$.ajax({
                url: "{% url 'dashboard_sp:fb_query' %}",
                data:{
                    'query':'execute'
                },
                dataType: 'json',
                success: function (data) {
                  if (data.statu === "success") {
                    const notification = document.getElementById('notification')
                    if (dataLenght < data.message.length){
                      dataLenght = data.message.length
                      let cpt = 0
                      document.querySelector('.quantity').textContent = dataLenght
                      notification.innerHTML = ''
                      for (item of data.message){
                        cpt++
                        if (cpt <= 3){
                          let div = document.createElement('div')
                          div.innerHTML = ''+
                            '<div class="notifi__item">'+
                            '<div class="bg-c1 img-cir img-40">'+
                            '<i class="zmdi zmdi-email-open"></i></div>'+
                            '<div class="content">'+
                            '<p>'+item+'</p>'+
                            '<span class="date">Publié sur votre page facebook</span>'
                            '</div></div>'
                            notification.appendChild(div)
                        }
                      }
                      cpt = 0 
                    }
                  } else console.log(data.message)
                }
              })
            , 5000)
    })()
</script>
{% endblock%}
    

dashboard/templates/dashboard/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{}}</title>
</head>
<body>
    <img src="" alt="" srcset="">
</body>
</html>